### ISSUE TITLE
New user type for crowd sourcing users

### ISSUE THREAD

**Issue by cziaarm** [Transkribus/TranskribusCore#5]
To identify whether a user is allowed to participate in editing a crowd source collection. My guess is this would be a per collection user_type (maybe "crowd" or "contributor"). So a user can be the owner or editor of one collection and a crowd-sourcer of another. Such users would *only* be able to edit pages via the crowd sourcing app. 

So in turn the app would need to identify itself when making requests to the REST API using a crowd-user session (?)

**Comment by kahlep** [comment]
Although we have agreed to just use the role "Transcriber" for this purpose, a user subscribing to a crowd collection now gets the role "CrowdTranscriber" after all.
There is one major advantage: Given the case that a crowd collection is withdrawn, i.e. the flag is set to 0, we are then able to remove all the crowd users without affecting the "normal" transcribers.

Blocking crowd transcribers which try to access a collection via the expert client is then also easy.

**Comment by kahlep** [comment]
The platform was now extended with means to set/unset the collection flag via the expert client.

@cziaarm In order to identify the client accessing the REST API, please add the following header value to each calls coming from your client: "clientId=2"
This will enable correct logging of the user actions (-> dashboard) as coming from the WebUI.
Also, we can then restrict crowdsourcing users from accessing via the expert client.
